openapi: 3.1.0
info:
  version: 1.0.0
  title: Stateset
  termsOfService: https://stateset.com/terms/
  contact:
    email: developers@stateset.com
    url: http://stateset.com/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://stateset.io/stateset_logo_8.png
  description: |
    This is the Stateset One API based on The OpenAPI Specification.
    # Introduction
    This API definition is intended to to be a good starting point for describing your API in [OpenAPI/Swagger format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md).
    # OpenAPI Specification
    The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can  understand and interact with the remote service with a minimal amount of implementation logic. Similar to what interfaces have done for lower-level programmin[...]
servers:
  - url: https://api.stateset.com/v1
    description: Production server
tags:
  - name: Accounts
    description: Operations related to accounts.
  - name: Bill Of Materials
    description: Operations related to bill of materials.
  - name: Bill Of Materials Line Items
    description: Operations related to bill of materials line items.
  - name: Case
    description: Operations related to cases.
  - name: Contacts
    description: Operations related to contacts.
  - name: Customers
    description: Operations related to customers.
  - name: CycleCount
    description: Operations related to cycle counts.
  - name: Inventory Items
    description: Operations related to inventory items.
  - name: Leads
    description: Operations related to leads.
  - name: Manufacture Orders
    description: Operations related to manufacturing orders.
  - name: Manufacture Order Line Items
    description: Operations related to manufacturing order line items.
  - name: Messages
    description: Operations related to messages.
  - name: Notes
    description: Operations related to notes.
  - name: PackingList
    description: Operations related to packing lists.
  - name: PackingListItem
    description: Operations related to packing list items.
  - name: Pick
    description: Operations related to picks.
  - name: PickLineItem
    description: Operations related to pick line items.
  - name: Returns
    description: Operations related to returns.
  - name: Return Line Items
    description: Operations related to return items.
  - name: Suppliers
    description: Operations related to suppliers.
  - name: User
    description: Operations related to users.
  - name: Vendors
    description: Operations related to vendors.
  - name: Warranties
    description: Operations related to warranties.
  - name: Warranty Line Items
    description: Operations related to warranty items.
  - name: Work Orders
    description: Operations related to work orders.
  - name: Work Order Line Items
    description: Operations related to work order line items.
paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get account by account name
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getAccountByName
      security:
        - main_auth:
            - read:accounts
        - api_key: []
  /accounts/{id}:
    get:
      tags:
        - Accounts
      summary: Get account by account name
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getAccountByName
      security:
        - main_auth:
            - read:accounts
        - api_key: []
  /billofmaterials:
    get:
      tags:
        - Bill Of Materials
      summary: Get bill of materials
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getBillofMaterials
      security:
        - main_auth:
            - read:bill of materials
        - api_key: []
    post:
      tags:
        - Bill Of Materials
      summary: Create a new bill of materials
      description: |
        Create a new bill of materials.
        This can only be done by the logged in bill of materials.
      operationId: createBillofMaterials
      security:
        - main_auth:
            - write:billofmaterials
  /billofmaterials/{id}:
    get:
      tags:
        - Bill Of Materials
      summary: Get bill of materials by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getBillOfMaterialsById
      security:
        - main_auth:
            - read:billofmaterials
        - api_key: []
    put:
      tags:
        - Bill Of Materials
      summary: Updated bill of materials
      description: This can only be done by the logged in user.
      operationId: updateBillOfMaterials
      security:
        - main_auth:
            - write:billofmaterials
    delete:
      tags:
        - Bill Of Materials
      summary: Delete Bill of Materials
      description: This can only be done by the logged in return.
      operationId: deleteBillOfMaterials
      security:
        - main_auth:
            - write:billofmaterials
  /customers:
    get:
      tags:
        - Customers
      summary: Get customer by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getCustomers
      security:
        - main_auth:
            - read:customers
        - api_key: []
  /customers/{id}:
    get:
      tags:
        - Notes
      summary: Get customers by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getCustomersById
      security:
        - main_auth:
            - read:customers
        - api_key: []
    put:
      tags:
        - Customers
      summary: Update customers
      description: This can only be done by the logged in user.
      operationId: updateCustomers
      security:
        - main_auth:
            - write:customers
    delete:
      tags:
        - Customers
      summary: Delete customers
      description: This can only be done by the logged in return.
      operationId: deleteCustomers
      security:
        - main_auth:
            - write:customers
  /billofmaterialsitems:
    get:
      tags:
        - Bill Of Materials Line Items
      summary: Get bill of materials item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getBillOfMaterialsItemById
      security:
        - main_auth:
            - read:billofmaterialsitems
        - api_key: []
  /billofmaterialsitems/{id}:
    get:
      tags:
        - Bill Of Materials Line Items
      summary: Get bill of materials line item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getBillOfMaterialsLineItemById
      security:
        - main_auth:
            - read:billofmaterialslineitems
        - api_key: []
    put:
      tags:
        - Bill Of Materials Line Items
      summary: Updated billofmaterials line item
      description: This can only be done by the logged in user.
      operationId: updateBillOfMaterialsLineItem
      security:
        - main_auth:
            - write:billofmaterialslineitems
  /inventoryitems:
    get:
      tags:
        - Inventory Items
      summary: Get inventory items
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getInventoryItems
      security:
        - main_auth:
            - read:inventory items
        - api_key: []
    post:
      tags:
        - Inventory Items
      summary: Create a new inventory items
      description: |
        Create a new inventory items.
        This can only be done by the logged in.
      operationId: createInventoryItems
      security:
        - main_auth:
            - write:inventory itemss
  /inventoryitems/{id}:
    get:
      tags:
        - Inventory Items
      summary: Get inventory items by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getInventoryItemById
      security:
        - main_auth:
            - read:inventoryitems
        - api_key: []
    put:
      tags:
        - Inventory Items
      summary: Updated inventory items
      description: This can only be done by the logged in user.
      operationId: updateInventoryItem
      security:
        - main_auth:
            - write:inventoryitems
    delete:
      tags:
        - Notes
      summary: Delete Inventory Items
      description: This can only be done by the logged in return.
      operationId: deleteInventoryItem
      security:
        - main_auth:
            - write:inventoryitems
  /manufactureorders:
    get:
      tags:
        - Manufacture Orders
      summary: Get account by manufacture order id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getManufactureOrders
      security:
        - main_auth:
            - read:manufactureorders
        - api_key: []
  /manufactureorders/{id}:
    get:
      tags:
        - Manufacture Orders
      summary: Get manufacture order by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getManufactureOrderById
      security:
        - main_auth:
            - read:manufactureorders
        - api_key: []
    put:
      tags:
        - Manufacture Orders
      summary: Updated manufacture order
      description: This can only be done by the logged in user.
      operationId: updateManufactureOrder
      security:
        - main_auth:
            - write:manufactureorders
  /manufactureorderitems:
    get:
      tags:
        - Manufacture Order Line Items
      summary: Get manufactureItem by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getManufactureItemById
      security:
        - main_auth:
            - read:manufactureItems
        - api_key: []
  /manufactureorderitems/{id}:
    get:
      tags:
        - Manufacture Order Line Items
      summary: Get manufacture line item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getManufactureLineItemById
      security:
        - main_auth:
            - read:manufacturelineitems
        - api_key: []
    put:
      tags:
        - Manufacture Order Line Items
      summary: Updated manufacture line item
      description: This can only be done by the logged in user.
      operationId: updateManufactureLineItem
      security:
        - main_auth:
            - write:manufacturelineitems
  /messages:
    get:
      tags:
        - Messages
      summary: Get messages
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getMessages
      security:
        - main_auth:
            - read:messages
        - api_key: []
    post:
      tags:
        - Messages
      summary: Create a new message
      description: |
        Create a new message.
        This can only be done by the logged in.
      operationId: createMessage
      security:
        - main_auth:
            - write:messages
  /messages/{id}:
    get:
      tags:
        - Messages
      summary: Get message by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getMessageById
      security:
        - main_auth:
            - read:messages
        - api_key: []
    put:
      tags:
        - Messages
      summary: Updated message
      description: This can only be done by the logged in user.
      operationId: updateMessage
      security:
        - main_auth:
            - write:messages
    delete:
      tags:
        - Messages
      summary: Delete message
      description: This can only be done by the logged in return.
      operationId: deleteMessage
      security:
        - main_auth:
            - write:messages
  /notes:
    get:
      tags:
        - Notes
      summary: Get notes
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getNotes
      security:
        - main_auth:
            - read:notes
        - api_key: []
    post:
      tags:
        - Notes
      summary: Create a new note
      description: |
        Create a new note.
        This can only be done by the logged in.
      operationId: createNote
      security:
        - main_auth:
            - write:notes
  /notes/{id}:
    get:
      tags:
        - Notes
      summary: Get notes by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getNotesById
      security:
        - main_auth:
            - read:notes
        - api_key: []
    put:
      tags:
        - Notes
      summary: Updated notes
      description: This can only be done by the logged in user.
      operationId: updateNotes
      security:
        - main_auth:
            - write:notes
    delete:
      tags:
        - Notes
      summary: Delete notes
      description: This can only be done by the logged in return.
      operationId: deleteNotes
      security:
        - main_auth:
            - write:notes
  /returns:
    get:
      tags:
        - Returns
      summary: Get returns
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getReturns
      security:
        - main_auth:
            - read:returns
        - api_key: []
    post:
      tags:
        - Returns
      summary: Create a new return
      description: |
        Create a new return.
        This can only be done by the logged in return.
      operationId: createReturn
      security:
        - main_auth:
            - write:returns
  /returns/{id}:
    get:
      tags:
        - Returns
      summary: Get return by id
      description: Get return by id with all details and items
      operationId: getReturnById
      security:
        - main_auth:
            - read:returns
        - api_key: []
    put:
      tags:
        - Returns
      summary: Updated return
      description: This can only be done by the logged in user.
      operationId: updateReturn
      security:
        - main_auth:
            - write:returns
    delete:
      tags:
        - Returns
      summary: Delete return
      description: This can only be done by the logged in return.
      operationId: deleteReturn
      security:
        - main_auth:
            - write:returns
  /returnitems:
    get:
      tags:
        - Return Line Items
      summary: Get returnItem by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getReturnItemById
      security:
        - main_auth:
            - read:returnItems
        - api_key: []
  /returnitems/{id}:
    get:
      tags:
        - Return Line Items
      summary: Get return line item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getReturnLineItemById
      security:
        - main_auth:
            - read:returnlineitems
        - api_key: []
    put:
      tags:
        - Return Line Items
      summary: Updated return line item
      description: This can only be done by the logged in user.
      operationId: updateReturnLineItem
      security:
        - main_auth:
            - write:returnlineitems
  /warranties:
    get:
      tags:
        - Warranties
      summary: Get warranties
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWarranties
      security:
        - main_auth:
            - read:warranties
        - api_key: []
    post:
      tags:
        - Warranties
      summary: Create a new warranty
      description: |
        Create a new return.
        This can only be done by the logged in return.
      operationId: createWarranty
      security:
        - main_auth:
            - write:warranties
  /warranties/{id}:
    get:
      tags:
        - Warranty
      summary: Get warranty by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWarrantyById
      security:
        - main_auth:
            - read:warranties
        - api_key: []
    put:
      tags:
        - Warranty
      summary: Updated warranty
      description: This can only be done by the logged in user.
      operationId: updateWarranty
      security:
        - main_auth:
            - write:warranties
    delete:
      tags:
        - Warranty
      summary: Delete warranty
      description: This can only be done by the logged in warranty.
      operationId: deleteWarranty
      security:
        - main_auth:
            - write:warranties
  /warrantyitems:
    get:
      tags:
        - Warranty Line Items
      summary: Get warrantyItem by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWarrantyItemById
      security:
        - main_auth:
            - read:warrantyItems
        - api_key: []
  /warrantyitems/{id}:
    get:
      tags:
        - Warranty Line Items
      summary: Get warranty line item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWarrantyLineItemById
      security:
        - main_auth:
            - read:warrantylineitems
        - api_key: []
    put:
      tags:
        - Warranty Line Items
      summary: Updated warranty line item
      description: This can only be done by the logged in user.
      operationId: updateWarrantyLineItem
      security:
        - main_auth:
            - write:warrantylineitems
  /workorders:
    get:
      tags:
        - Work Orders
      summary: Get account by work order id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWorkOrdes
      security:
        - main_auth:
            - read:workorders
        - api_key: []
  /workorders/{id}:
    get:
      tags:
        - Work Orders
      summary: Get work order by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWorkOrderById
      security:
        - main_auth:
            - read:workorders
        - api_key: []
    put:
      tags:
        - Work Orders
      summary: Updated work order
      description: This can only be done by the logged in user.
      operationId: updateWorkOrder
      security:
        - main_auth:
            - write:workorders
  /workorderitems:
    get:
      tags:
        - Work Order Line Items
      summary: Get work order item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWorkItemById
      security:
        - main_auth:
            - read:workItems
        - api_key: []
  /workorderitems/{id}:
    get:
      tags:
        - Work Order Line Items
      summary: Get work line item by id
      description: |
        Some description of the operation.
        You can use `Markdown` here.
      operationId: getWorkLineItemById
      security:
        - main_auth:
            - read:worklineitems
        - api_key: []
    put:
      tags:
        - Work Order Line Items
      summary: Updated work line item
      description: This can only be done by the logged in user.
      operationId: updateWorkLineItem
      security:
        - main_auth:
            - write:worklineitems
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.stateset.com/v1/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic